version: '3.2'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./docker_data/redis-data:/var/lib/redis

  app:
    build: .
    depends_on:
      - redis
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    environment:
      GO111MODULE: "ON"


